# Generated by Django 5.1.2 on 2024-11-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='upside_downside',
            field=models.FloatField(null=True),
        ),
    ]
