# Generated by Django 5.1.4 on 2024-12-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_proj', '0003_stockdata_bollinger_high_stockdata_bollinger_low_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='bollinger_high',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='bollinger_low',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='ema_12',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='ema_26',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='ema_9',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='macd',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='macd_signal',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='moving_average_10',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='moving_average_50',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='rsi',
        ),
    ]
